name: ETL Dolar cotizacion

on:
  #schedule:
   # - cron: '0 13 * * *'  # Todos los días a las 13:00 UTC (10:00 AM en Argentina)
  workflow_dispatch:      # Permite ejecución manual desde la UI de GitHub

jobs:
  etl-job:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      DB: ${{ secrets.DB }}
      SCHEMA: ${{ secrets.SCHEMA }}
      
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script ETL
        run: |
          python app.py
